index:
    pattern:  /
    defaults: { _controller: HostelMainBundle:Default:index }

ticket:
    pattern: /ticket/{id}
    defaults: { _controller: HostelMainBundle:Default:ticket }

terms:
    pattern: /terms
    defaults: { _controller: HostelMainBundle:Default:terms }


registration_success:
    pattern: /registration_success
    defaults: { _controller: HostelMainBundle:Default:registrationSuccess }

login:
    pattern:  /login
    defaults: { _controller: HostelMainBundle:Default:login }

payConnection:
    pattern:  /pay/connection
    defaults: { _controller: HostelMainBundle:Default:pay, connection: true }

pay:
    pattern:  /pay/{year}/{month}
    defaults: { _controller: HostelMainBundle:Default:pay }