Hostel\MainBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: 'Этот логин уже используется'
    properties:
        username:
            - NotBlank: ~
        firstname:
            - NotBlank: ~
        lastname:
            - NotBlank: ~
        hostel:
            - NotBlank: ~
        room:
            - NotBlank: ~
        groupNumber:
            - NotBlank: ~
        enabled:
            - NotNull: ~